const fs = require("fs");
const path = require("path");

const schema = [
  "// This is your Prisma schema file",
  "",
  "generator client {",
  '  provider = "prisma-client-js"',
  "}",
  "",
  "datasource db {",
  '  provider = "postgresql"',
  '  url      = env("DATABASE_URL")',
  "}",
  "",
  "model User {",
  "  id        String   @id @default(cuid())",
  "  name      String",
  "  email     String   @unique",
  "  password  String",
  "  role      UserRole @default(REVIEWER)",
  "  createdAt DateTime @default(now())",
  "  updatedAt DateTime @updatedAt",
  "",
  '  assignedBriefs Brief[]            @relation("AssignedBriefs")',
  "  events         BriefEvent[]",
  "  notes          BriefNote[]",
  "  overrides      EstimateOverride[]",
  "",
  "  @@index([email])",
  "}",
  "",
  "model Brief {",
  "  id              String          @id @default(cuid())",
  "  title           String",
  "  description     String          @db.Text",
  "  budgetRange     BudgetRange",
  "  timelineUrgency TimelineUrgency",
  "  contactName     String",
  "  contactEmail    String",
  "  source          BriefSource     @default(FORM)",
  "  stage           BriefStage      @default(NEW)",
  "  assigneeId      String?",
  "  createdAt       DateTime        @default(now())",
  "  updatedAt       DateTime        @updatedAt",
  "",
  "  analysis BriefAnalysis?",
  '  assignee User?          @relation("AssignedBriefs", fields: [assigneeId], references: [id])',
  "  events   BriefEvent[]",
  "  notes    BriefNote[]",
  "",
  "  @@index([createdAt])",
  "  @@index([source])",
  "  @@index([stage])",
  "  @@index([assigneeId])",
  "}",
  "",
  "model BriefAnalysis {",
  "  id              String           @id @default(cuid())",
  "  briefId         String           @unique",
  "  brief           Brief            @relation(fields: [briefId], references: [id])",
  "  status          AnalysisStatus   @default(PENDING)",
  "  features        Json",
  "  category        ProjectCategory?",
  "  effortMin       Int?",
  "  effortMax       Int?",
  "  techStack       Json?",
  "  complexityScore Int?",
  "  rawResponse     String?          @db.Text",
  "  errorMessage    String?",
  "  createdAt       DateTime         @default(now())",
  "  updatedAt       DateTime         @updatedAt",
  "",
  "  override EstimateOverride?",
  "",
  "  @@index([briefId])",
  "  @@index([status])",
  "}",
  "",
  "model BriefEvent {",
  "  id        String         @id @default(cuid())",
  "  briefId   String",
  "  userId    String?",
  "  type      BriefEventType",
  "  payload   Json",
  "  createdAt DateTime       @default(now())",
  "",
  "  brief Brief @relation(fields: [briefId], references: [id])",
  "  user  User? @relation(fields: [userId], references: [id])",
  "",
  "  @@index([briefId])",
  "  @@index([createdAt])",
  "}",
  "",
  "model BriefNote {",
  "  id        String   @id @default(cuid())",
  "  briefId   String",
  "  authorId  String",
  "  content   String   @db.Text",
  "  parentId  String?",
  "  createdAt DateTime @default(now())",
  "  updatedAt DateTime @updatedAt",
  "",
  "  brief   Brief       @relation(fields: [briefId], references: [id])",
  "  author  User        @relation(fields: [authorId], references: [id])",
  '  parent  BriefNote?  @relation("NoteReplies", fields: [parentId], references: [id])',
  '  replies BriefNote[] @relation("NoteReplies")',
  "",
  "  @@index([briefId])",
  "  @@index([parentId])",
  "}",
  "",
  "model EstimateOverride {",
  "  id              String   @id @default(cuid())",
  "  analysisId      String   @unique",
  "  overriddenById  String",
  "  effortMin       Int",
  "  effortMax       Int",
  "  techStack       Json",
  "  complexityScore Int",
  "  reason          String   @db.Text",
  "  createdAt       DateTime @default(now())",
  "",
  "  analysis     BriefAnalysis @relation(fields: [analysisId], references: [id])",
  "  overriddenBy User          @relation(fields: [overriddenById], references: [id])",
  "",
  "  @@index([analysisId])",
  "}",
  "",
  "enum UserRole {",
  "  ADMIN",
  "  REVIEWER",
  "}",
  "",
  "enum BriefStage {",
  "  NEW",
  "  UNDER_REVIEW",
  "  PROPOSAL_SENT",
  "  WON",
  "  ARCHIVED",
  "}",
  "",
  "enum BriefEventType {",
  "  STAGE_CHANGE",
  "  ASSIGNMENT",
  "  NOTE_ADDED",
  "}",
  "",
  "enum BudgetRange {",
  "  UNDER_5K",
  "  BETWEEN_5K_15K",
  "  BETWEEN_15K_50K",
  "  OVER_50K",
  "}",
  "",
  "enum TimelineUrgency {",
  "  ASAP",
  "  ONE_TO_THREE_MONTHS",
  "  THREE_TO_SIX_MONTHS",
  "  SIX_PLUS_MONTHS",
  "}",
  "",
  "enum BriefSource {",
  "  FORM",
  "  WEBHOOK",
  "}",
  "",
  "enum AnalysisStatus {",
  "  PENDING",
  "  COMPLETED",
  "  FAILED",
  "}",
  "",
  "enum ProjectCategory {",
  "  WEB_APP",
  "  MOBILE",
  "  AI_ML",
  "  AUTOMATION",
  "  INTEGRATION",
  "}",
].join("\n");

const dest = path.join(__dirname, "..", "prisma", "schema.prisma");
fs.writeFileSync(dest, schema, "utf8");
console.log("Schema written to", dest);
